# Generated by Django 3.0.8 on 2022-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_founder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
