# Generated by Django 3.0.8 on 2022-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20221023_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
    ]
