# Generated by Django 3.0.8 on 2022-09-13 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouts_topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouts_topic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
