# Generated by Django 3.0.8 on 2022-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0002_auto_20220913_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouts_topic',
            name='icon_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
