# Generated by Django 3.0.8 on 2022-09-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0004_maintenance_detail_maintenance_topic_servicepage_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage_detail',
            name='page_head',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
