# Generated by Django 3.0.8 on 2022-09-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0006_founders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Founders',
            new_name='Founder',
        ),
    ]
