# Generated by Django 3.0.8 on 2022-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0008_founder_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
    ]
