# Generated by Django 3.0.8 on 2022-09-17 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0010_testimonial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
