# Generated by Django 3.0.8 on 2022-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0011_auto_20220917_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('enable', models.BooleanField(default=False)),
                ('icon_label', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
