# Generated by Django 3.0.8 on 2022-09-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_founder'),
        ('aakaar_admin', '0012_foundersocialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='profession',
        ),
        migrations.AddField(
            model_name='founder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
