# Generated by Django 3.0.8 on 2022-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0014_clientprojecttype_clientworkingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone_number', models.IntegerField()),
                ('project_type', models.CharField(max_length=30)),
                ('working_type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
