# Generated by Django 3.0.8 on 2022-09-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0015_projectrequest_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest_form',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aakaar_admin.ClientProjectType'),
        ),
        migrations.AlterField(
            model_name='projectrequest_form',
            name='working_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aakaar_admin.ClientWorkingType'),
        ),
    ]
