# Generated by Django 5.2.1 on 2025-05-19 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0016_auto_20220917_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest_form',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('project_code', models.CharField(max_length=300)),
                ('project_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aakaar_admin.clientprojecttype')),
                ('working_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aakaar_admin.clientworkingtype')),
            ],
        ),
    ]
