# Generated by Django 5.2.1 on 2025-05-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0017_projectrequest_form_comments_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
