# Generated by Django 5.2.1 on 2025-05-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0019_project_discreption_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discreption',
            field=models.TextField(),
        ),
    ]
