# Generated by Django 5.2.1 on 2025-05-31 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakaar_admin', '0021_blog_blogdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('icon_class', models.CharField(choices=[('fas fa-paper-plane', 'Paper Plane'), ('fas fa-gem', 'Gem'), ('fas fa-rocket', 'Rocket')], max_length=50)),
                ('view_link', models.URLField(default='#', help_text='Link to detail or purchase page')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='aakaar_admin.pricingplan')),
            ],
        ),
    ]
