# Generated by Django 5.2.1 on 2025-06-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
