# Generated by Django 3.0.8 on 2022-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
