# Generated by Django 3.0.8 on 2022-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_socialmedia_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon_label',
            field=models.CharField(default='text', max_length=50),
            preserve_default=False,
        ),
    ]
