# Generated by Django 3.0.8 on 2022-10-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220913_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='compnayDescription',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
