# Generated by Django 3.0.8 on 2022-10-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_companydetail_compnaydescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetail',
            old_name='compnayDescription',
            new_name='companyDescription',
        ),
    ]
