# Generated by Django 3.0.8 on 2022-10-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221016_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='companyLocationUrl',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30161.356782908842!2d72.80604999311709!3d19.100214325932026!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c994afbc6de9%3A0xd36760e4a1a77177!2sJuhu%20Beach!5e0!3m2!1sen!2sin!4v1655879706390!5m2!1sen!2sin'),
            preserve_default=False,
        ),
    ]
