# Generated by Django 3.0.8 on 2022-10-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_companydetail_companylocationurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='companyLocationUrl',
            field=models.TextField(),
        ),
    ]
