# Generated by Django 5.2.1 on 2025-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221016_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBannerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_heading', models.CharField(help_text='e.g., AakarDevelopers', max_length=100)),
                ('main_heading', models.CharField(help_text='e.g., Website Development', max_length=150)),
                ('description', models.TextField(help_text='e.g., Short paragraph below the heading')),
            ],
        ),
    ]
