# Generated by Django 5.2.1 on 2025-06-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactsection_contactinfobox'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='app_section/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'App Section',
                'verbose_name_plural': 'App Sections',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('flaticon-calendar', 'Calendar'), ('flaticon-mobile-app', 'Mobile App'), ('flaticon-patient', 'Patient'), ('flaticon-broadcasting', 'Broadcasting')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('app_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.appsection')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
    ]
